worker_processes auto;
events { worker_connections 1024; }

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;

    server {
        listen 8080;
        server_name localhost;

        # 1. 伪装网页 (默认访问)
        location / {
            root   /var/www/html;
            index  index.html;
        }

        # 2. 🌟 新增：信息面板 (访问 你的路径/info)
        # 例如路径是 /secret，访问地址就是 https://域名/secret/info
        location $$WSPATH$$/info {
            default_type text/html;
            alias /var/www/html/info.html;
        }

        # 3. 节点流量转发
        location $$WSPATH$$ {
            proxy_redirect off;
            proxy_pass http://127.0.0.1:8081;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }
    }
}
